// Consent storage for the self-hosted c15t backend mounted at /api/c15t.
// Generated by `pnpm consent:generate`; regenerate it when upgrading
// @c15t/backend and add a Drizzle migration for any change.
/* eslint-disable @typescript-eslint/no-unused-vars */

import { pgTable, varchar, text, timestamp, boolean, json, foreignKey } from "drizzle-orm/pg-core"
import { relations } from "drizzle-orm"

export const c15t_subject = pgTable("c15t_subject", {
  id: varchar("id", { length: 255 }).primaryKey().notNull(),
  externalId: text("externalId"),
  identityProvider: text("identityProvider"),
  createdAt: timestamp("createdAt").notNull().defaultNow(),
  updatedAt: timestamp("updatedAt").notNull().defaultNow(),
  tenantId: text("tenantId")
})

export const c15t_subjectRelations = relations(c15t_subject, ({ one, many }) => ({
  consents: many(c15t_consent, {
    relationName: "consent_subject"
  }),
  auditLogs: many(c15t_auditLog, {
    relationName: "auditLog_subject"
  })
}));

export const c15t_domain = pgTable("c15t_domain", {
  id: varchar("id", { length: 255 }).primaryKey().notNull(),
  name: text("name").notNull(),
  createdAt: timestamp("createdAt").notNull().defaultNow(),
  updatedAt: timestamp("updatedAt").notNull().defaultNow(),
  tenantId: text("tenantId")
})

export const c15t_domainRelations = relations(c15t_domain, ({ one, many }) => ({
  consents: many(c15t_consent, {
    relationName: "consent_domain"
  })
}));

export const c15t_consentPolicy = pgTable("c15t_consentPolicy", {
  id: varchar("id", { length: 255 }).primaryKey().notNull(),
  version: text("version").notNull(),
  type: text("type").notNull(),
  hash: text("hash"),
  effectiveDate: timestamp("effectiveDate").notNull(),
  isActive: boolean("isActive").notNull(),
  createdAt: timestamp("createdAt").notNull().defaultNow(),
  tenantId: text("tenantId")
})

export const c15t_consentPolicyRelations = relations(c15t_consentPolicy, ({ one, many }) => ({
  consents: many(c15t_consent, {
    relationName: "consent_consentPolicy"
  })
}));

export const c15t_runtimePolicyDecision = pgTable("c15t_runtimePolicyDecision", {
  id: varchar("id", { length: 255 }).primaryKey().notNull(),
  tenantId: text("tenantId"),
  policyId: text("policyId").notNull(),
  fingerprint: text("fingerprint").notNull(),
  matchedBy: text("matchedBy").notNull(),
  countryCode: text("countryCode"),
  regionCode: text("regionCode"),
  jurisdiction: text("jurisdiction").notNull(),
  language: text("language"),
  model: text("model").notNull(),
  policyI18n: json("policyI18n"),
  uiMode: text("uiMode"),
  bannerUi: json("bannerUi"),
  dialogUi: json("dialogUi"),
  categories: json("categories"),
  preselectedCategories: json("preselectedCategories"),
  proofConfig: json("proofConfig"),
  dedupeKey: text("dedupeKey").unique().notNull(),
  createdAt: timestamp("createdAt").notNull().defaultNow()
})

export const c15t_runtimePolicyDecisionRelations = relations(c15t_runtimePolicyDecision, ({ one, many }) => ({
  consents: many(c15t_consent, {
    relationName: "consent_runtimePolicyDecision"
  })
}));

export const c15t_consentPurpose = pgTable("c15t_consentPurpose", {
  id: varchar("id", { length: 255 }).primaryKey().notNull(),
  code: text("code").notNull(),
  createdAt: timestamp("createdAt").notNull().defaultNow(),
  updatedAt: timestamp("updatedAt").notNull().defaultNow(),
  tenantId: text("tenantId")
})

export const c15t_consent = pgTable("c15t_consent", {
  id: varchar("id", { length: 255 }).primaryKey().notNull(),
  subjectId: text("subjectId").notNull(),
  domainId: text("domainId").notNull(),
  policyId: text("policyId"),
  purposeIds: json("purposeIds").notNull(),
  metadata: json("metadata"),
  ipAddress: text("ipAddress"),
  userAgent: text("userAgent"),
  givenAt: timestamp("givenAt").notNull().defaultNow(),
  validUntil: timestamp("validUntil"),
  jurisdiction: text("jurisdiction"),
  jurisdictionModel: text("jurisdictionModel"),
  tcString: text("tcString"),
  uiSource: text("uiSource"),
  consentAction: text("consentAction"),
  runtimePolicyDecisionId: text("runtimePolicyDecisionId"),
  runtimePolicySource: text("runtimePolicySource"),
  tenantId: text("tenantId")
}, (table) => [
  foreignKey({
    columns: [table.subjectId],
    foreignColumns: [c15t_subject.id],
    name: "consent_subject_subject_fk"
  }).onUpdate("restrict").onDelete("restrict"),
  foreignKey({
    columns: [table.domainId],
    foreignColumns: [c15t_domain.id],
    name: "consent_domain_domain_fk"
  }).onUpdate("restrict").onDelete("restrict"),
  foreignKey({
    columns: [table.policyId],
    foreignColumns: [c15t_consentPolicy.id],
    name: "consent_consentPolicy_policy_fk"
  }).onUpdate("restrict").onDelete("restrict"),
  foreignKey({
    columns: [table.runtimePolicyDecisionId],
    foreignColumns: [c15t_runtimePolicyDecision.id],
    name: "consent_runtimePolicyDecision_runtimePolicyDecision_fk"
  }).onUpdate("restrict").onDelete("restrict")
])

export const c15t_consentRelations = relations(c15t_consent, ({ one, many }) => ({
  subject: one(c15t_subject, {
    relationName: "consent_subject",
    fields: [c15t_consent.subjectId],
    references: [c15t_subject.id]
  }),
  domain: one(c15t_domain, {
    relationName: "consent_domain",
    fields: [c15t_consent.domainId],
    references: [c15t_domain.id]
  }),
  policy: one(c15t_consentPolicy, {
    relationName: "consent_consentPolicy",
    fields: [c15t_consent.policyId],
    references: [c15t_consentPolicy.id]
  }),
  runtimePolicyDecision: one(c15t_runtimePolicyDecision, {
    relationName: "consent_runtimePolicyDecision",
    fields: [c15t_consent.runtimePolicyDecisionId],
    references: [c15t_runtimePolicyDecision.id]
  })
}));

export const c15t_auditLog = pgTable("c15t_auditLog", {
  id: varchar("id", { length: 255 }).primaryKey().notNull(),
  entityType: text("entityType").notNull(),
  entityId: text("entityId").notNull(),
  actionType: text("actionType").notNull(),
  subjectId: text("subjectId"),
  ipAddress: text("ipAddress"),
  userAgent: text("userAgent"),
  changes: json("changes"),
  metadata: json("metadata"),
  createdAt: timestamp("createdAt").notNull().defaultNow(),
  tenantId: text("tenantId")
}, (table) => [
  foreignKey({
    columns: [table.subjectId],
    foreignColumns: [c15t_subject.id],
    name: "auditLog_subject_subject_fk"
  }).onUpdate("restrict").onDelete("restrict")
])

export const c15t_auditLogRelations = relations(c15t_auditLog, ({ one, many }) => ({
  subject: one(c15t_subject, {
    relationName: "auditLog_subject",
    fields: [c15t_auditLog.subjectId],
    references: [c15t_subject.id]
  })
}));

export const private_c15t_settings = pgTable("private_c15t_settings", {
  id: varchar("id", { length: 255 }).primaryKey().notNull(),
  version: varchar("version", { length: 255 }).notNull().default("2.0.0")
})
